"""
Properties by which issue connections can be ordered.
"""
enum IssueOrderField {
  """
  Order issues by comment count
  """
  COMMENTS

  """
  Order issues by creation time
  """
  CREATED_AT

  """
  Order issues by update time
  """
  UPDATED_AT
}
